############################################
#       A bare-bones MySQL database        #
#   Designed for 42 PHP Piscine, Day 05    #
############################################

version: '3'

services:

  db:
    build: .
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  shell:
    build: /shell/.
    links: 
      - db:db
    restart: always