###################################################
#       A containerized version of 42 PAMP        #
#  Includes dependencies needed to build Camagru  #
###################################################

version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    environment:
        - MYSQL_DATABASE:camagru
        - MYSQL_USER:root
        - MYSQL_ROOT_PASSWORD:root

  php:
    build: ./php
    ports:
      - "5000:80"
    volumes:
      - ./src:/docker-pamp/src
    working_dir: /docker-pamp/src
    links:
      - db:db
    environment:
        - MYSQL_DATABASE:camagru
        - MYSQL_USER:root
        - MYSQL_ROOT_PASSWORD:root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80

volumes:
  db_data:

#------
# USAGE
#------
# TO BUILD : docker-compuse up
# TO TEST : visit http://[machine ip]:8081
#   should display PHPmyadmin login
