# This is based on a tutorial available at https://www.youtube.com/watch?v=Qw9zlE3t8Ko

version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service

#------
# USAGE
#------
# TO BUILD : docker-compuse up
# TO TEST : visit http://[machine ip]:5000
#   Edit either api.py or index.php and refresh
#   will update live because of volumes